# Generated by Django 4.1.4 on 2023-05-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CriminalName', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('CriminalPic', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
