# Generated by Django 4.1.4 on 2023-05-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_mycollection_record_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycollection',
            name='Criminality',
            field=models.CharField(default='', max_length=100),
        ),
    ]
